train_features = [
"srch_id", # 1
"date_time", # 2
"site_id", # 3
"visitor_location_country_id", # 4
"visitor_hist_starrating", # 5
"visitor_hist_adr_usd", # 6
"prop_country_id", # 7
"prop_id", # 8
"prop_starrating", # 9
"prop_review_score", # 10
"prop_brand_bool", # 11
"prop_location_score1", # 12
"prop_location_score2", # 13
"prop_log_historical_price", # 14
"position", # 15
"price_usd", # 16
"promotion_flag", # 17
"srch_destination_id", # 18
"srch_length_of_stay", # 19
"srch_booking_window", # 20
"srch_adults_count", # 21
"srch_children_count", # 22
"srch_room_count", # 23
"srch_saturday_night_bool", # 24
"srch_query_affinity_score", # 25
"orig_destination_distance", # 26
"random_bool", # 27
"comp1_rate", # 28
"comp1_inv", # 29
"comp1_rate_percent_diff", # 30
"comp2_rate", # 31
"comp2_inv", # 32
"comp2_rate_percent_diff", # 33
"comp3_rate", # 34
"comp3_inv", # 35
"comp3_rate_percent_diff", # 36
"comp4_rate", # 37
"comp4_inv", # 38
"comp4_rate_percent_diff", # 39
"comp5_rate", # 40
"comp5_inv", # 41
"comp5_rate_percent_diff", # 42
"comp6_rate", # 43
"comp6_inv", # 44
"comp6_rate_percent_diff", # 45
"comp7_rate", # 46
"comp7_inv", # 47
"comp7_rate_percent_diff", # 48
"comp8_rate", # 49
"comp8_inv", # 50
"comp8_rate_percent_diff", # 51
"click_bool", # 52
"gross_bookings_usd", # 53
"booking_bool", # 54
]

train_features_map = dict([(v, i+1) for i, v in enumerate(train_features)])

# print "\n".join(["\"%s\", # %s" % (k, v) for (k,v) in sorted(test_features_map.iteritems(), key = lambda x: x[1])])
test_features = [
"srch_id", # 1
"date_time", # 2
"site_id", # 3
"visitor_location_country_id", # 4
"visitor_hist_starrating", # 5
"visitor_hist_adr_usd", # 6
"prop_country_id", # 7
"prop_id", # 8
"prop_starrating", # 9
"prop_review_score", # 10
"prop_brand_bool", # 11
"prop_location_score1", # 12
"prop_location_score2", # 13
"prop_log_historical_price", # 14
"price_usd", # 15
"promotion_flag", # 16
"srch_destination_id", # 17
"srch_length_of_stay", # 18
"srch_booking_window", # 19
"srch_adults_count", # 20
"srch_children_count", # 21
"srch_room_count", # 22
"srch_saturday_night_bool", # 23
"srch_query_affinity_score", # 24
"orig_destination_distance", # 25
"random_bool", # 26
"comp1_rate", # 27
"comp1_inv", # 28
"comp1_rate_percent_diff", # 29
"comp2_rate", # 30
"comp2_inv", # 31
"comp2_rate_percent_diff", # 32
"comp3_rate", # 33
"comp3_inv", # 34
"comp3_rate_percent_diff", # 35
"comp4_rate", # 36
"comp4_inv", # 37
"comp4_rate_percent_diff", # 38
"comp5_rate", # 39
"comp5_inv", # 40
"comp5_rate_percent_diff", # 41
"comp6_rate", # 42
"comp6_inv", # 43
"comp6_rate_percent_diff", # 44
"comp7_rate", # 45
"comp7_inv", # 46
"comp7_rate_percent_diff", # 47
"comp8_rate", # 48
"comp8_inv", # 49
"comp8_rate_percent_diff", # 50
]

test_features_map = dict([(v, i+1) for i, v in enumerate(test_features)])
